version: '3.8'
services:

  postgres:
    image: postgres:15
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: pazar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network
    command: >
      postgres -c listen_addresses='*'

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    driver: bridge
